name: Publish to NPM

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/run-tests.yml
    name: Run Tests

  build-and-publish:
    name: Build and Publish
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - run: |
          yarn install
          yarn prebuild
          yarn build
        name: Build
      - run: npm publish --access public --dry-run
        name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
